### PR TITLE
Revert Reverted ArbitrationRole

### PR DESCRIPTION
**Pull request by gichiba**
This is a resurrection of #630, which died in the hustle between gorli and mainnet. 

I'm not certain I did this right according to our rebase standards. Using the latest develop, I created a new branch, and did an interactive rebase on the commit before krono's `revert ArbitrationRole`, and dropped only that commit in the rebase. Which should have restored everything that was approved in #630, based on the latest develop branch.

### CODE REVIEW

**Comment by kronosapiens** [comment]
Mm, in this case I would say the best thing to do would be to take your original branch and:

1. `git rebase -i HEAD~5` and just `squash` all those original commit into one commit
2. rebase that new commit all the way onto develop
3. Make a PR as normal

In other words, don't worry about resurrecting the first time these changes were merged, let's just treat them as new code and handle them that way. It'll be the same outcome but easier on the commit log.

**Comment by gichiba** [comment]
oh tay

**Comment by gichiba** [comment]
Closing as a new PR has been opened by the suggestion of krono

**Comment by kronosapiens** [comment]
Nice! Although for the record you could have also updated this PR in-place.

**Comment by elenadimitrova** [comment]
Was this just a bad rebase of the original branch?

**Comment by kronosapiens** [comment]
Seems like it, no harm no foul though.

**Comment by elenadimitrova** [comment]
Sure, I'd just rather rebase properly than move work to a secondary PR.

**Comment by gichiba** [comment]
Well now I know that

**Pull request closed without merging**
