### PR TITLE
Doc fixes collection

### PR DESCRIPTION
**Pull request by chmanie**
I opened this to fix a couple of issues with the current docs.

So far:

- [x] Use relative paths for images for SEO reasons

- [x] Add / Update rating system for tasks and auth permissions

This is stil a WIP.

### CODE REVIEW

**Comment by chmanie** [comment]
@gichiba do you know more about the progress of this?

**Comment by gichiba** [comment]
Ok I think that should be what we want to include in this... I just *still* am having trouble with the rebase... @chmanie can I (sheepishly) ask you to rebase and merge?

**Comment by chmanie** [comment]
If there's no conflicts like this time it's pretty straightforward:

```
cd colonyNetwork
git checkout docs/minor-doc-fixes
git pull --rebase
git rebase origin/develop
git push --force-with-lease
```

**Comment by chmanie** [comment]
You can review your own PR, griffin and merge it if you like. I can't see anything wrong.

**Pull request merged**
