### PR TITLE
Use npm-based colonyToken

### PR DESCRIPTION
**Pull request by chmanie**
To generate the ABIs for ColonyJS, `yarn` is still necessary due to the `colonyToken` repo. I created an `npm` version of the token here: https://github.com/JoinColony/colonyToken/pull/59

This PR points `lib/colonyToken` to the PR branch but will later be replaced with the `master` branch of colonyToken.

### CODE REVIEW

**Comment by kronosapiens** [comment]
@chmanie I've merged colonyToken#59 so you can update this pull request to point to `master`

**Comment by chmanie** [comment]
@kronosapiens Cool thank you! I'm wondering about the other open PRs in colonyToken. Should we also merge some of them before updating the reference?

**Comment by kronosapiens** [comment]
@chmanie good point, I'll clean up some of those upgrade PRs today

**Comment by kronosapiens** [comment]
@chmanie I've merged the old dependency upgrades. The new ones (opened in the last 24 hours) are failing so I'll circle back around to those later. I'd say point to `colonyToken/master` and we can merge this.

**Review by kronosapiens — DISMISSED** [review]

**Review by kronosapiens — APPROVED** [review]

**Pull request merged**
