### PR TITLE
Moving token weighted voting to EtherRouter pattern

### PR DESCRIPTION
**Pull request by markhainesii**
This feature has been partially refactored and needs reviewing @elenadimitrova 

I have mainly worked on the new storage model, decided as struct mappings, and implemented them up to `addVoteSecret()`. This function has a bit more complexity and so far I have added the `Vote` struct for its storage.

### CODE REVIEW

**Comment by markhainesii** [comment]
@elenadimitrova does a linked list start with a zero entry for each new poll or is it continual? I'm getting back to this when I can.

**Comment by elenadimitrova** [comment]
I need to look into this in more detail @markhainesii but I won't have a chance over the next ~2 weeks. Before I can get to it properly though I'd really like to see some of the tests ported across as that's where design flaws normally surface.

**Comment by elenadimitrova** [comment]
@markhainesii let's reopen this when it's ready to be reviewed. Branch will of course remain and there we can continually review at given checkpoints.

**Comment by markhainesii** [comment]
Ok. I'm working on the tests for the voting which all need to pass. Then maybe I can push this code before the token locking tests.

**Comment by markhainesii** [comment]
@elenadimitrova I have updated the contracts (styling and linted) and provided test file `token-weighted-voting.js`. Not all tests are complete, but I have managed to pass those tests to do with 
poll creation. You'll see (at line 189) the start of the vote submission tests that currently fail. I am finding it a little tricky to adapt my `Vote` struct variables to the correct insertion order, and this is where I'd appreciate your review if you're happy to reopen the PR.

**Comment by markhainesii** [comment]
Do you have any comments on this @elenadimitrova I am aware of the launch next month, so I have considered that you are busy.

**Comment by elenadimitrova** [comment]
Apologies for the radio silence @markhainesii I will look at this this week. I have been bashing at some urgent problems yesterday and this morning which are likely to take a little longer.

**Comment by elenadimitrova** [comment]
I'm not able to reopen this because the branch on your remote was recreated perhaps? 

screen shot 2018-11-29 at 19 49 57

If you can open a new one perhaps https://github.com/JoinColony/colonyNetwork/compare/develop...markhainesii:feature/90-token-weighted-voting

**Comment by elenadimitrova** [comment]
Some initial notes below:

- Why are these complex storage mappings necessary:
```
mapping(uint256 => mapping(uint256 => Poll)) public polls;
mapping(address => mapping(uint256 => mapping(uint256 => Vote))) public votes;`
```
The normalisation level here is going to make these impossible to work with. For example in `polls`, you are mapping `pollId` to `pollOptionId` to `Poll`, meaning that for a poll with 2 options storage looks like
1 => 0 => {
  '0': 'simple yes/no vote',
  '1': '',
  '2': <BN: 2>,
  '3': <BN: 0>,
  '4': <BN: 0>,
  '5': <BN: 0>,
  '6': <BN: 0>,
  '7': <BN: 0>,
  description: 'simple yes/no vote',
  pollOptionDescription: '',
  pollOptionCount: <BN: 2>,
  pollStartTime: <BN: 0>,
  pollCloseTime: <BN: 0>,
  pollStatus: <BN: 0>,
  voteWeight: <BN: 0>,
  voteCount: <BN: 0> }

1 => 1 =>  {
  '0': '',
  '1': 'Yes',
  '2': <BN: 0>,
  '3': <BN: 0>,
  '4': <BN: 0>,
  '5': <BN: 0>,
  '6': <BN: 0>,
  '7': <BN: 0>,
  description: '',
  pollOptionDescription: 'Yes',
  pollOptionCount: <BN: 0>,
  pollStartTime: <BN: 0>,
  pollCloseTime: <BN: 0>,
  pollStatus: <BN: 0>,
  voteWeight: <BN: 0>,
  voteCount: <BN: 0> }

1 => 2 =>  {
  '0': '',
  '1': 'No',
  '2': <BN: 0>,
  '3': <BN: 0>,
  '4': <BN: 0>,
  '5': <BN: 0>,
  '6': <BN: 0>,
  '7': <BN: 0>,
  description: '',
  pollOptionDescription: 'No',
  pollOptionCount: <BN: 0>,
  pollStartTime: <BN: 0>,
  pollCloseTime: <BN: 0>,
  pollStatus: <BN: 0>,
  voteWeight: <BN: 0>,
  voteCount: <BN: 0> }
```

**Comment by markhainesii** [comment]
Thanks for taking a look. Yes, overall there needs to be some separation into single mappings perhaps. I have been following the complex lookup patterns from the old contract - which is confusing. 

I'm quite new to Solidity too, so I'll be slapping myself a few times!

**Comment by elenadimitrova** [comment]
The `EternalStorage` data storage pattern necessitated the lowest level of normalisation in order to maximise the simplicity of the immutable data storage contract. This is not the case here. I admit you've wilfully dived in the deep end of contract development with this work :)
Try to follow the best practices around data normalisation but using the data structures Solidity provides and it should be fine. If you start implementing a function and it looks off, then something in your design is wrong, can be your data structure or your function separation of logic or something yet bigger.

**Comment by markhainesii** [comment]
@elenadimitrova I saw that you couldn't reopen this PR. I had to force push my last commits, so shall I recreate?

**Comment by markhainesii** [comment]
@elenadimitrova I am trying to avoid a lot of truffle compile errors which I think is to do with the compiler version. Should I be running docker? If so, what tag do you specify in your image pulls?

**Comment by elenadimitrova** [comment]
If you have rebased then that would use solc 0.4.23 as specified in our [`truffle.js`](https://github.com/JoinColony/colonyNetwork/blob/develop/truffle.js#L36)

**Comment by markhainesii** [comment]
@elenadimitrova ok done. I tried compiling again and the errors are still prevalent for contracts such as dappsys/math.sol, gnosis/MultiSigWallet.sol - it's mainly the third-party contracts. I am using your version of node but with truffle 5.0.0-beta.2. I hoped this wouldn't turn into an issue here.

**Comment by elenadimitrova** [comment]
@markhainesii is this just compilation "warnings" rather than "errors"? Like the ones we have in build atm https://circleci.com/gh/JoinColony/colonyNetwork/5162 , see "running unit tests" step.

**Comment by markhainesii** [comment]
It's the same warnings, then a compilation fail. But, I have looked again and found some of my own natspec comments causing a `DocstringParsingError`. Compilation now builds 😌

**Comment by markhainesii** [comment]
@elenadimitrova I've revised the storage problem for poll creation and hopefully it's simpler now - using one primary key and removing variables that were previously sitting redundant. `struct Poll` is now smaller and I've added `struct PollOption` for recursive actions per poll.

**Comment by elenadimitrova** [comment]
@markhainesii How would the storage look like now for the example I gave [here](https://github.com/JoinColony/colonyNetwork/pull/380#issuecomment-442943379)?

**Comment by markhainesii** [comment]
I should've reconsidered that last push and done this first. I imagine the state would look this way once a poll has opened. Don't see a need for a separate poll option struct.
```
// Create a poll
1 => {
  description: 'simple yes/no vote',
  pollOptionDescription: '',
  pollStartTime: <BN: 0>,
  pollCloseTime: <BN: 0>,
  pollStatus: <BN: 0>
}

// Add option 1
1 => {
  description: 'simple yes/no vote',
  pollOptionDescription: [
    0: 'Yes',
  ]
  pollStartTime: <BN: 0>,
  pollCloseTime: <BN: 0>,
  pollStatus: <BN: 0>
}

// Add option 2
1 => {
  description: 'simple yes/no vote',
  pollOptionDescription: [
    0: 'Yes',
    1: 'No'
  ]
  pollStartTime: <BN: 0>,
  pollCloseTime: <BN: 0>,
  pollStatus: <BN: 0>
}

// Open poll
1 => {
  description: 'simple yes/no vote',
  pollOptionDescription: [
    0: 'Yes',
    1: 'No'
  ]
  pollStartTime: 43200,
  pollCloseTime: 86424,
  pollStatus: 1
}
```

**Comment by elenadimitrova** [comment]
I can't see how this is true with the latest I'm looking at in the storage layout since a Poll is defined as
```
struct Poll {
    string description;
    uint256 pollStartTime;
    uint256 pollCloseTime;
    uint256 pollStatus;
  }
```
and it is being stored as `mapping(uint256 => Poll) public polls;`

**Pull request closed without merging**
