### PR TITLE
Upgrade node to 14.21.3

### PR DESCRIPTION
**Pull request by chmanie**
This PR upgrades node to the latest 14.x release, incorporating important bugfixes and CVE fixes.

### CODE REVIEW

**Comment by area** [comment]
Can you test this with [the dapp repo](https://github.com/JoinColony/colonyDapp) ? I recall us having issues with mismatched versions in the past, though I admit that was probably a major version difference.

**Comment by chmanie** [comment]
Yeah I really don't think this should impact the dApp. But I can test I guess

**Comment by area** [comment]
Having tried it with both the Dapp and the CDapp, both will require changes for this to work without throwing incompatible version errors.

**Comment by chmanie** [comment]
I guess we stay on the old version then?

**Comment by area** [comment]
Superseded by #1242

**Pull request closed without merging**
